### to run the following API use REST Client VS code extension or use postman

###   POST cityname without json

POST http://localhost:5000/weather/place HTTP/1.1
content-type: application/json


###   POST cityname with json

POST http://localhost:5000/weather/place HTTP/1.1
content-type: application/json

{
    "place": "bangalore"
}

###   POST cityname with json and empty parameter

POST http://localhost:5000/weather/place HTTP/1.1
content-type: application/json

{
    "place": ""
}

###   POST cityname with json and invalid parameter 

POST http://localhost:5000/weather/place HTTP/1.1
content-type: application/json

{
    "place": "2345"
}